cc_library(
    name = "autos",
    srcs = [
        "left_one_steal_two_ball_auto_command.cc",
        "left_two_ball_auto_command.cc",
        "right_five_ball_auto_command.cc",
        "right_two_ball_auto_command.cc",
    ],
    hdrs = [
        "left_one_steal_two_ball_auto_command.h",
        "left_two_ball_auto_command.h",
        "right_five_ball_auto_command.h",
        "right_two_ball_auto_command.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//robot:field",
        "//robot/commands",
    ],
)
